/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Desribes professionnal party
 */
@ApiModel(description = "Desribes professionnal party")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-04T15:17:57.729789200+02:00[Europe/Paris]")
public class BusinessProfessionnalPartyProfessionnal {
  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  private String customerId;

  public static final String SERIALIZED_NAME_CUSTOMER_REF = "customerRef";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_REF)
  private String customerRef;

  public BusinessProfessionnalPartyProfessionnal() { 
  }

  public BusinessProfessionnalPartyProfessionnal customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Internal Identifier of organisation
   * @return customerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "PRO-8996786873", value = "Internal Identifier of organisation")

  public String getCustomerId() {
    return customerId;
  }


  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public BusinessProfessionnalPartyProfessionnal customerRef(String customerRef) {
    
    this.customerRef = customerRef;
    return this;
  }

   /**
   * External identifier of organisation (i.e. CUSTOMER)
   * @return customerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "CUSTOMER NUMBER", value = "External identifier of organisation (i.e. CUSTOMER)")

  public String getCustomerRef() {
    return customerRef;
  }


  public void setCustomerRef(String customerRef) {
    this.customerRef = customerRef;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessProfessionnalPartyProfessionnal businessProfessionnalPartyProfessionnal = (BusinessProfessionnalPartyProfessionnal) o;
    return Objects.equals(this.customerId, businessProfessionnalPartyProfessionnal.customerId) &&
        Objects.equals(this.customerRef, businessProfessionnalPartyProfessionnal.customerRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, customerRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessProfessionnalPartyProfessionnal {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    customerRef: ").append(toIndentedString(customerRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customerId");
    openapiFields.add("customerRef");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BusinessProfessionnalPartyProfessionnal
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (BusinessProfessionnalPartyProfessionnal.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in BusinessProfessionnalPartyProfessionnal is not found in the empty JSON string", BusinessProfessionnalPartyProfessionnal.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BusinessProfessionnalPartyProfessionnal.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BusinessProfessionnalPartyProfessionnal` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("customerId") != null && !jsonObj.get("customerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerId").toString()));
      }
      if (jsonObj.get("customerRef") != null && !jsonObj.get("customerRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerRef").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BusinessProfessionnalPartyProfessionnal.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BusinessProfessionnalPartyProfessionnal' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BusinessProfessionnalPartyProfessionnal> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BusinessProfessionnalPartyProfessionnal.class));

       return (TypeAdapter<T>) new TypeAdapter<BusinessProfessionnalPartyProfessionnal>() {
           @Override
           public void write(JsonWriter out, BusinessProfessionnalPartyProfessionnal value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BusinessProfessionnalPartyProfessionnal read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BusinessProfessionnalPartyProfessionnal given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BusinessProfessionnalPartyProfessionnal
  * @throws IOException if the JSON string is invalid with respect to BusinessProfessionnalPartyProfessionnal
  */
  public static BusinessProfessionnalPartyProfessionnal fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BusinessProfessionnalPartyProfessionnal.class);
  }

 /**
  * Convert an instance of BusinessProfessionnalPartyProfessionnal to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

