/*
 * Travel Contract
 * The Travel Contract Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessPayment;
import org.openapitools.client.model.DeferredBilling;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-04T15:17:57.729789200+02:00[Europe/Paris]")
public class ContractRequestCustom extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ContractRequestCustom.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ContractRequestCustom.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ContractRequestCustom' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DeferredBilling> adapterDeferredBilling = gson.getDelegateAdapter(this, TypeToken.get(DeferredBilling.class));

            return (TypeAdapter<T>) new TypeAdapter<ContractRequestCustom>() {
                @Override
                public void write(JsonWriter out, ContractRequestCustom value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `DeferredBilling`
                    if (value.getActualInstance() instanceof DeferredBilling) {
                        JsonObject obj = adapterDeferredBilling.toJsonTree((DeferredBilling)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: DeferredBilling");
                }

                @Override
                public ContractRequestCustom read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize DeferredBilling
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DeferredBilling.validateJsonObject(jsonObject);
                        actualAdapter = adapterDeferredBilling;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DeferredBilling'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for DeferredBilling failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DeferredBilling'", e);
                    }

                    if (match == 1) {
                        ContractRequestCustom ret = new ContractRequestCustom();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for ContractRequestCustom: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public ContractRequestCustom() {
        super("oneOf", Boolean.FALSE);
    }

    public ContractRequestCustom(DeferredBilling o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DeferredBilling", new GenericType<DeferredBilling>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return ContractRequestCustom.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * DeferredBilling
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof DeferredBilling) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be DeferredBilling");
    }

    /**
     * Get the actual instance, which can be the following:
     * DeferredBilling
     *
     * @return The actual instance (DeferredBilling)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `DeferredBilling`. If the actual instance is not `DeferredBilling`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DeferredBilling`
     * @throws ClassCastException if the instance is not `DeferredBilling`
     */
    public DeferredBilling getDeferredBilling() throws ClassCastException {
        return (DeferredBilling)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ContractRequestCustom
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with DeferredBilling
    try {
      DeferredBilling.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for DeferredBilling failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for ContractRequestCustom with oneOf schemas: DeferredBilling. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonObj.toString()));
    }
  }

 /**
  * Create an instance of ContractRequestCustom given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ContractRequestCustom
  * @throws IOException if the JSON string is invalid with respect to ContractRequestCustom
  */
  public static ContractRequestCustom fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContractRequestCustom.class);
  }

 /**
  * Convert an instance of ContractRequestCustom to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

