/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.BusinessSellerEFacturation;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes seller organisation &amp; contact
 */
@ApiModel(description = "Describes seller organisation & contact")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-04T15:12:40.475542300+02:00[Europe/Paris]")
public class BusinessSeller {
  public static final String SERIALIZED_NAME_SELLER_REF = "sellerRef";
  @SerializedName(SERIALIZED_NAME_SELLER_REF)
  private String sellerRef;

  public static final String SERIALIZED_NAME_E_FACTURATION = "eFacturation";
  @SerializedName(SERIALIZED_NAME_E_FACTURATION)
  private BusinessSellerEFacturation eFacturation;

  public static final String SERIALIZED_NAME_CONTACT_PERSON = "contactPerson";
  @SerializedName(SERIALIZED_NAME_CONTACT_PERSON)
  private BusinessPerson contactPerson;

  public static final String SERIALIZED_NAME_CONTACT_ADDRESS = "contactAddress";
  @SerializedName(SERIALIZED_NAME_CONTACT_ADDRESS)
  private BusinessAddress contactAddress;

  public BusinessSeller() { 
  }

  public BusinessSeller sellerRef(String sellerRef) {
    
    this.sellerRef = sellerRef;
    return this;
  }

   /**
   * External reference of seller
   * @return sellerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "esgi SA", value = "External reference of seller")

  public String getSellerRef() {
    return sellerRef;
  }


  public void setSellerRef(String sellerRef) {
    this.sellerRef = sellerRef;
  }


  public BusinessSeller eFacturation(BusinessSellerEFacturation eFacturation) {
    
    this.eFacturation = eFacturation;
    return this;
  }

   /**
   * Get eFacturation
   * @return eFacturation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessSellerEFacturation geteFacturation() {
    return eFacturation;
  }


  public void seteFacturation(BusinessSellerEFacturation eFacturation) {
    this.eFacturation = eFacturation;
  }


  public BusinessSeller contactPerson(BusinessPerson contactPerson) {
    
    this.contactPerson = contactPerson;
    return this;
  }

   /**
   * Get contactPerson
   * @return contactPerson
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessPerson getContactPerson() {
    return contactPerson;
  }


  public void setContactPerson(BusinessPerson contactPerson) {
    this.contactPerson = contactPerson;
  }


  public BusinessSeller contactAddress(BusinessAddress contactAddress) {
    
    this.contactAddress = contactAddress;
    return this;
  }

   /**
   * Get contactAddress
   * @return contactAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessAddress getContactAddress() {
    return contactAddress;
  }


  public void setContactAddress(BusinessAddress contactAddress) {
    this.contactAddress = contactAddress;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessSeller businessSeller = (BusinessSeller) o;
    return Objects.equals(this.sellerRef, businessSeller.sellerRef) &&
        Objects.equals(this.eFacturation, businessSeller.eFacturation) &&
        Objects.equals(this.contactPerson, businessSeller.contactPerson) &&
        Objects.equals(this.contactAddress, businessSeller.contactAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sellerRef, eFacturation, contactPerson, contactAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessSeller {\n");
    sb.append("    sellerRef: ").append(toIndentedString(sellerRef)).append("\n");
    sb.append("    eFacturation: ").append(toIndentedString(eFacturation)).append("\n");
    sb.append("    contactPerson: ").append(toIndentedString(contactPerson)).append("\n");
    sb.append("    contactAddress: ").append(toIndentedString(contactAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sellerRef");
    openapiFields.add("eFacturation");
    openapiFields.add("contactPerson");
    openapiFields.add("contactAddress");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BusinessSeller
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (BusinessSeller.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in BusinessSeller is not found in the empty JSON string", BusinessSeller.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BusinessSeller.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BusinessSeller` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("sellerRef") != null && !jsonObj.get("sellerRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sellerRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sellerRef").toString()));
      }
      // validate the optional field `eFacturation`
      if (jsonObj.getAsJsonObject("eFacturation") != null) {
        BusinessSellerEFacturation.validateJsonObject(jsonObj.getAsJsonObject("eFacturation"));
      }
      // validate the optional field `contactPerson`
      if (jsonObj.getAsJsonObject("contactPerson") != null) {
        BusinessPerson.validateJsonObject(jsonObj.getAsJsonObject("contactPerson"));
      }
      // validate the optional field `contactAddress`
      if (jsonObj.getAsJsonObject("contactAddress") != null) {
        BusinessAddress.validateJsonObject(jsonObj.getAsJsonObject("contactAddress"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BusinessSeller.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BusinessSeller' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BusinessSeller> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BusinessSeller.class));

       return (TypeAdapter<T>) new TypeAdapter<BusinessSeller>() {
           @Override
           public void write(JsonWriter out, BusinessSeller value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BusinessSeller read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BusinessSeller given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BusinessSeller
  * @throws IOException if the JSON string is invalid with respect to BusinessSeller
  */
  public static BusinessSeller fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BusinessSeller.class);
  }

 /**
  * Convert an instance of BusinessSeller to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

