/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Necessary for e-Invoicing &amp; e-Reporting
 */
@ApiModel(description = "Necessary for e-Invoicing & e-Reporting")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-04T15:12:40.475542300+02:00[Europe/Paris]")
public class BusinessSellerEFacturation {
  public static final String SERIALIZED_NAME_SIREN = "siren";
  @SerializedName(SERIALIZED_NAME_SIREN)
  private String siren;

  public static final String SERIALIZED_NAME_TVA_INTRACOMMUNAUTAIRE = "tvaIntracommunautaire";
  @SerializedName(SERIALIZED_NAME_TVA_INTRACOMMUNAUTAIRE)
  private String tvaIntracommunautaire;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public BusinessSellerEFacturation() { 
  }

  public BusinessSellerEFacturation siren(String siren) {
    
    this.siren = siren;
    return this;
  }

   /**
   * Get siren
   * @return siren
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "356000000", value = "")

  public String getSiren() {
    return siren;
  }


  public void setSiren(String siren) {
    this.siren = siren;
  }


  public BusinessSellerEFacturation tvaIntracommunautaire(String tvaIntracommunautaire) {
    
    this.tvaIntracommunautaire = tvaIntracommunautaire;
    return this;
  }

   /**
   * Get tvaIntracommunautaire
   * @return tvaIntracommunautaire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FR39356000000", value = "")

  public String getTvaIntracommunautaire() {
    return tvaIntracommunautaire;
  }


  public void setTvaIntracommunautaire(String tvaIntracommunautaire) {
    this.tvaIntracommunautaire = tvaIntracommunautaire;
  }


  public BusinessSellerEFacturation country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FRANCE", value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessSellerEFacturation businessSellerEFacturation = (BusinessSellerEFacturation) o;
    return Objects.equals(this.siren, businessSellerEFacturation.siren) &&
        Objects.equals(this.tvaIntracommunautaire, businessSellerEFacturation.tvaIntracommunautaire) &&
        Objects.equals(this.country, businessSellerEFacturation.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(siren, tvaIntracommunautaire, country);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessSellerEFacturation {\n");
    sb.append("    siren: ").append(toIndentedString(siren)).append("\n");
    sb.append("    tvaIntracommunautaire: ").append(toIndentedString(tvaIntracommunautaire)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("siren");
    openapiFields.add("tvaIntracommunautaire");
    openapiFields.add("country");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BusinessSellerEFacturation
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (BusinessSellerEFacturation.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in BusinessSellerEFacturation is not found in the empty JSON string", BusinessSellerEFacturation.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BusinessSellerEFacturation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BusinessSellerEFacturation` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("siren") != null && !jsonObj.get("siren").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `siren` to be a primitive type in the JSON string but got `%s`", jsonObj.get("siren").toString()));
      }
      if (jsonObj.get("tvaIntracommunautaire") != null && !jsonObj.get("tvaIntracommunautaire").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tvaIntracommunautaire` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tvaIntracommunautaire").toString()));
      }
      if (jsonObj.get("country") != null && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BusinessSellerEFacturation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BusinessSellerEFacturation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BusinessSellerEFacturation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BusinessSellerEFacturation.class));

       return (TypeAdapter<T>) new TypeAdapter<BusinessSellerEFacturation>() {
           @Override
           public void write(JsonWriter out, BusinessSellerEFacturation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BusinessSellerEFacturation read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BusinessSellerEFacturation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BusinessSellerEFacturation
  * @throws IOException if the JSON string is invalid with respect to BusinessSellerEFacturation
  */
  public static BusinessSellerEFacturation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BusinessSellerEFacturation.class);
  }

 /**
  * Convert an instance of BusinessSellerEFacturation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

