/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessProfessionnalPartyProfessionnal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes professionnal organisation
 */
@ApiModel(description = "Describes professionnal organisation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-04T15:12:40.475542300+02:00[Europe/Paris]")
public class BusinessProfessionnalParty {
  public static final String SERIALIZED_NAME_PROFESSIONNAL = "professionnal";
  @SerializedName(SERIALIZED_NAME_PROFESSIONNAL)
  private BusinessProfessionnalPartyProfessionnal professionnal;

  public BusinessProfessionnalParty() { 
  }

  public BusinessProfessionnalParty professionnal(BusinessProfessionnalPartyProfessionnal professionnal) {
    
    this.professionnal = professionnal;
    return this;
  }

   /**
   * Get professionnal
   * @return professionnal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessProfessionnalPartyProfessionnal getProfessionnal() {
    return professionnal;
  }


  public void setProfessionnal(BusinessProfessionnalPartyProfessionnal professionnal) {
    this.professionnal = professionnal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessProfessionnalParty businessProfessionnalParty = (BusinessProfessionnalParty) o;
    return Objects.equals(this.professionnal, businessProfessionnalParty.professionnal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(professionnal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessProfessionnalParty {\n");
    sb.append("    professionnal: ").append(toIndentedString(professionnal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("professionnal");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BusinessProfessionnalParty
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (BusinessProfessionnalParty.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in BusinessProfessionnalParty is not found in the empty JSON string", BusinessProfessionnalParty.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BusinessProfessionnalParty.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BusinessProfessionnalParty` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `professionnal`
      if (jsonObj.getAsJsonObject("professionnal") != null) {
        BusinessProfessionnalPartyProfessionnal.validateJsonObject(jsonObj.getAsJsonObject("professionnal"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BusinessProfessionnalParty.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BusinessProfessionnalParty' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BusinessProfessionnalParty> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BusinessProfessionnalParty.class));

       return (TypeAdapter<T>) new TypeAdapter<BusinessProfessionnalParty>() {
           @Override
           public void write(JsonWriter out, BusinessProfessionnalParty value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BusinessProfessionnalParty read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BusinessProfessionnalParty given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BusinessProfessionnalParty
  * @throws IOException if the JSON string is invalid with respect to BusinessProfessionnalParty
  */
  public static BusinessProfessionnalParty fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BusinessProfessionnalParty.class);
  }

 /**
  * Convert an instance of BusinessProfessionnalParty to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

