/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OperationResponseAllOfInvoice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-04T15:12:40.475542300+02:00[Europe/Paris]")
public class OperationResponseAllOfInvoice {
  public static final String SERIALIZED_NAME_INVOICE_REF = "invoiceRef";
  @SerializedName(SERIALIZED_NAME_INVOICE_REF)
  private String invoiceRef;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private LocalDate createdAt;

  public static final String SERIALIZED_NAME_COMMING_SOON = "commingSoon";
  @SerializedName(SERIALIZED_NAME_COMMING_SOON)
  private Object commingSoon;

  public OperationResponseAllOfInvoice() { 
  }

  public OperationResponseAllOfInvoice invoiceRef(String invoiceRef) {
    
    this.invoiceRef = invoiceRef;
    return this;
  }

   /**
   * Get invoiceRef
   * @return invoiceRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInvoiceRef() {
    return invoiceRef;
  }


  public void setInvoiceRef(String invoiceRef) {
    this.invoiceRef = invoiceRef;
  }


  public OperationResponseAllOfInvoice createdAt(LocalDate createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(LocalDate createdAt) {
    this.createdAt = createdAt;
  }


  public OperationResponseAllOfInvoice commingSoon(Object commingSoon) {
    
    this.commingSoon = commingSoon;
    return this;
  }

   /**
   * Get commingSoon
   * @return commingSoon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getCommingSoon() {
    return commingSoon;
  }


  public void setCommingSoon(Object commingSoon) {
    this.commingSoon = commingSoon;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationResponseAllOfInvoice operationResponseAllOfInvoice = (OperationResponseAllOfInvoice) o;
    return Objects.equals(this.invoiceRef, operationResponseAllOfInvoice.invoiceRef) &&
        Objects.equals(this.createdAt, operationResponseAllOfInvoice.createdAt) &&
        Objects.equals(this.commingSoon, operationResponseAllOfInvoice.commingSoon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoiceRef, createdAt, commingSoon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationResponseAllOfInvoice {\n");
    sb.append("    invoiceRef: ").append(toIndentedString(invoiceRef)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    commingSoon: ").append(toIndentedString(commingSoon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("invoiceRef");
    openapiFields.add("createdAt");
    openapiFields.add("commingSoon");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OperationResponseAllOfInvoice
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (OperationResponseAllOfInvoice.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in OperationResponseAllOfInvoice is not found in the empty JSON string", OperationResponseAllOfInvoice.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OperationResponseAllOfInvoice.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OperationResponseAllOfInvoice` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("invoiceRef") != null && !jsonObj.get("invoiceRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `invoiceRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("invoiceRef").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OperationResponseAllOfInvoice.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OperationResponseAllOfInvoice' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OperationResponseAllOfInvoice> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OperationResponseAllOfInvoice.class));

       return (TypeAdapter<T>) new TypeAdapter<OperationResponseAllOfInvoice>() {
           @Override
           public void write(JsonWriter out, OperationResponseAllOfInvoice value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OperationResponseAllOfInvoice read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OperationResponseAllOfInvoice given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OperationResponseAllOfInvoice
  * @throws IOException if the JSON string is invalid with respect to OperationResponseAllOfInvoice
  */
  public static OperationResponseAllOfInvoice fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OperationResponseAllOfInvoice.class);
  }

 /**
  * Convert an instance of OperationResponseAllOfInvoice to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

