/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OperationRequestOrderOrderItemsInnerProductItemsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-04T15:12:40.475542300+02:00[Europe/Paris]")
public class OperationRequestOrderOrderItemsInnerProductItemsInner {
  public static final String SERIALIZED_NAME_PRODUCT_REF = "productRef";
  @SerializedName(SERIALIZED_NAME_PRODUCT_REF)
  private String productRef;

  public static final String SERIALIZED_NAME_PRODUCT_LABEL = "productLabel";
  @SerializedName(SERIALIZED_NAME_PRODUCT_LABEL)
  private String productLabel;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity;

  public static final String SERIALIZED_NAME_PACKAGING = "packaging";
  @SerializedName(SERIALIZED_NAME_PACKAGING)
  private String packaging;

  public static final String SERIALIZED_NAME_UNIT_PRICE = "unitPrice";
  @SerializedName(SERIALIZED_NAME_UNIT_PRICE)
  private BigDecimal unitPrice;

  public static final String SERIALIZED_NAME_VAT_RATE = "vatRate";
  @SerializedName(SERIALIZED_NAME_VAT_RATE)
  private BigDecimal vatRate;

  public static final String SERIALIZED_NAME_AMOUNT_WITHOUT_TAX = "amountWithoutTax";
  @SerializedName(SERIALIZED_NAME_AMOUNT_WITHOUT_TAX)
  private BigDecimal amountWithoutTax;

  public static final String SERIALIZED_NAME_AMOUNT_TAX = "amountTax";
  @SerializedName(SERIALIZED_NAME_AMOUNT_TAX)
  private BigDecimal amountTax;

  public static final String SERIALIZED_NAME_AMOUNT_WITH_TAX = "amountWithTax";
  @SerializedName(SERIALIZED_NAME_AMOUNT_WITH_TAX)
  private BigDecimal amountWithTax;

  public static final String SERIALIZED_NAME_AMOUNT_ECO_PARTICIPATION = "amountEcoParticipation";
  @SerializedName(SERIALIZED_NAME_AMOUNT_ECO_PARTICIPATION)
  private BigDecimal amountEcoParticipation;

  public OperationRequestOrderOrderItemsInnerProductItemsInner() { 
  }

  public OperationRequestOrderOrderItemsInnerProductItemsInner productRef(String productRef) {
    
    this.productRef = productRef;
    return this;
  }

   /**
   * Get productRef
   * @return productRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProductRef() {
    return productRef;
  }


  public void setProductRef(String productRef) {
    this.productRef = productRef;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner productLabel(String productLabel) {
    
    this.productLabel = productLabel;
    return this;
  }

   /**
   * Get productLabel
   * @return productLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProductLabel() {
    return productLabel;
  }


  public void setProductLabel(String productLabel) {
    this.productLabel = productLabel;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner packaging(String packaging) {
    
    this.packaging = packaging;
    return this;
  }

   /**
   * Get packaging
   * @return packaging
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPackaging() {
    return packaging;
  }


  public void setPackaging(String packaging) {
    this.packaging = packaging;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner unitPrice(BigDecimal unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getUnitPrice() {
    return unitPrice;
  }


  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner vatRate(BigDecimal vatRate) {
    
    this.vatRate = vatRate;
    return this;
  }

   /**
   * Get vatRate
   * @return vatRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getVatRate() {
    return vatRate;
  }


  public void setVatRate(BigDecimal vatRate) {
    this.vatRate = vatRate;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner amountWithoutTax(BigDecimal amountWithoutTax) {
    
    this.amountWithoutTax = amountWithoutTax;
    return this;
  }

   /**
   * Get amountWithoutTax
   * @return amountWithoutTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmountWithoutTax() {
    return amountWithoutTax;
  }


  public void setAmountWithoutTax(BigDecimal amountWithoutTax) {
    this.amountWithoutTax = amountWithoutTax;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner amountTax(BigDecimal amountTax) {
    
    this.amountTax = amountTax;
    return this;
  }

   /**
   * Get amountTax
   * @return amountTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmountTax() {
    return amountTax;
  }


  public void setAmountTax(BigDecimal amountTax) {
    this.amountTax = amountTax;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner amountWithTax(BigDecimal amountWithTax) {
    
    this.amountWithTax = amountWithTax;
    return this;
  }

   /**
   * Get amountWithTax
   * @return amountWithTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmountWithTax() {
    return amountWithTax;
  }


  public void setAmountWithTax(BigDecimal amountWithTax) {
    this.amountWithTax = amountWithTax;
  }


  public OperationRequestOrderOrderItemsInnerProductItemsInner amountEcoParticipation(BigDecimal amountEcoParticipation) {
    
    this.amountEcoParticipation = amountEcoParticipation;
    return this;
  }

   /**
   * Necessary for e-Invoicing
   * @return amountEcoParticipation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Necessary for e-Invoicing")

  public BigDecimal getAmountEcoParticipation() {
    return amountEcoParticipation;
  }


  public void setAmountEcoParticipation(BigDecimal amountEcoParticipation) {
    this.amountEcoParticipation = amountEcoParticipation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationRequestOrderOrderItemsInnerProductItemsInner operationRequestOrderOrderItemsInnerProductItemsInner = (OperationRequestOrderOrderItemsInnerProductItemsInner) o;
    return Objects.equals(this.productRef, operationRequestOrderOrderItemsInnerProductItemsInner.productRef) &&
        Objects.equals(this.productLabel, operationRequestOrderOrderItemsInnerProductItemsInner.productLabel) &&
        Objects.equals(this.quantity, operationRequestOrderOrderItemsInnerProductItemsInner.quantity) &&
        Objects.equals(this.packaging, operationRequestOrderOrderItemsInnerProductItemsInner.packaging) &&
        Objects.equals(this.unitPrice, operationRequestOrderOrderItemsInnerProductItemsInner.unitPrice) &&
        Objects.equals(this.vatRate, operationRequestOrderOrderItemsInnerProductItemsInner.vatRate) &&
        Objects.equals(this.amountWithoutTax, operationRequestOrderOrderItemsInnerProductItemsInner.amountWithoutTax) &&
        Objects.equals(this.amountTax, operationRequestOrderOrderItemsInnerProductItemsInner.amountTax) &&
        Objects.equals(this.amountWithTax, operationRequestOrderOrderItemsInnerProductItemsInner.amountWithTax) &&
        Objects.equals(this.amountEcoParticipation, operationRequestOrderOrderItemsInnerProductItemsInner.amountEcoParticipation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productRef, productLabel, quantity, packaging, unitPrice, vatRate, amountWithoutTax, amountTax, amountWithTax, amountEcoParticipation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationRequestOrderOrderItemsInnerProductItemsInner {\n");
    sb.append("    productRef: ").append(toIndentedString(productRef)).append("\n");
    sb.append("    productLabel: ").append(toIndentedString(productLabel)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    packaging: ").append(toIndentedString(packaging)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    vatRate: ").append(toIndentedString(vatRate)).append("\n");
    sb.append("    amountWithoutTax: ").append(toIndentedString(amountWithoutTax)).append("\n");
    sb.append("    amountTax: ").append(toIndentedString(amountTax)).append("\n");
    sb.append("    amountWithTax: ").append(toIndentedString(amountWithTax)).append("\n");
    sb.append("    amountEcoParticipation: ").append(toIndentedString(amountEcoParticipation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("productRef");
    openapiFields.add("productLabel");
    openapiFields.add("quantity");
    openapiFields.add("packaging");
    openapiFields.add("unitPrice");
    openapiFields.add("vatRate");
    openapiFields.add("amountWithoutTax");
    openapiFields.add("amountTax");
    openapiFields.add("amountWithTax");
    openapiFields.add("amountEcoParticipation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OperationRequestOrderOrderItemsInnerProductItemsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (OperationRequestOrderOrderItemsInnerProductItemsInner.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in OperationRequestOrderOrderItemsInnerProductItemsInner is not found in the empty JSON string", OperationRequestOrderOrderItemsInnerProductItemsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OperationRequestOrderOrderItemsInnerProductItemsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OperationRequestOrderOrderItemsInnerProductItemsInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("productRef") != null && !jsonObj.get("productRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productRef").toString()));
      }
      if (jsonObj.get("productLabel") != null && !jsonObj.get("productLabel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productLabel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productLabel").toString()));
      }
      if (jsonObj.get("packaging") != null && !jsonObj.get("packaging").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `packaging` to be a primitive type in the JSON string but got `%s`", jsonObj.get("packaging").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OperationRequestOrderOrderItemsInnerProductItemsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OperationRequestOrderOrderItemsInnerProductItemsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OperationRequestOrderOrderItemsInnerProductItemsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OperationRequestOrderOrderItemsInnerProductItemsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<OperationRequestOrderOrderItemsInnerProductItemsInner>() {
           @Override
           public void write(JsonWriter out, OperationRequestOrderOrderItemsInnerProductItemsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OperationRequestOrderOrderItemsInnerProductItemsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OperationRequestOrderOrderItemsInnerProductItemsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OperationRequestOrderOrderItemsInnerProductItemsInner
  * @throws IOException if the JSON string is invalid with respect to OperationRequestOrderOrderItemsInnerProductItemsInner
  */
  public static OperationRequestOrderOrderItemsInnerProductItemsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OperationRequestOrderOrderItemsInnerProductItemsInner.class);
  }

 /**
  * Convert an instance of OperationRequestOrderOrderItemsInnerProductItemsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

