/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BusinessParticularParty;
import org.openapitools.client.model.BusinessParticularPartyParticular;
import org.openapitools.client.model.BusinessProfessionnalParty;
import org.openapitools.client.model.BusinessProfessionnalPartyProfessionnal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessBuyerParty
 */
public class BusinessBuyerPartyTest {
    private final BusinessBuyerParty model = new BusinessBuyerParty();

    /**
     * Model tests for BusinessBuyerParty
     */
    @Test
    public void testBusinessBuyerParty() {
        // TODO: test BusinessBuyerParty
    }

    /**
     * Test the property 'professionnal'
     */
    @Test
    public void professionnalTest() {
        // TODO: test professionnal
    }

    /**
     * Test the property 'particular'
     */
    @Test
    public void particularTest() {
        // TODO: test particular
    }

}
