/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Invoice;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InvoicesGet200Response
 */
public class InvoicesGet200ResponseTest {
    private final InvoicesGet200Response model = new InvoicesGet200Response();

    /**
     * Model tests for InvoicesGet200Response
     */
    @Test
    public void testInvoicesGet200Response() {
        // TODO: test InvoicesGet200Response
    }

    /**
     * Test the property 'invoices'
     */
    @Test
    public void invoicesTest() {
        // TODO: test invoices
    }

}
