/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.OperationsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OperationsGet200Response
 */
public class OperationsGet200ResponseTest {
    private final OperationsGet200Response model = new OperationsGet200Response();

    /**
     * Model tests for OperationsGet200Response
     */
    @Test
    public void testOperationsGet200Response() {
        // TODO: test OperationsGet200Response
    }

    /**
     * Test the property 'orders'
     */
    @Test
    public void ordersTest() {
        // TODO: test orders
    }

}
