/*
 * Travel Billing
 * The Travel Invoicing Application System
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BusinessAddress;
import org.openapitools.client.model.BusinessPerson;
import org.openapitools.client.model.OperationRequestOrderOrderItemsInnerProductItemsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OperationRequestOrderOrderItemsInner
 */
public class OperationRequestOrderOrderItemsInnerTest {
    private final OperationRequestOrderOrderItemsInner model = new OperationRequestOrderOrderItemsInner();

    /**
     * Model tests for OperationRequestOrderOrderItemsInner
     */
    @Test
    public void testOperationRequestOrderOrderItemsInner() {
        // TODO: test OperationRequestOrderOrderItemsInner
    }

    /**
     * Test the property 'shipmentAddress'
     */
    @Test
    public void shipmentAddressTest() {
        // TODO: test shipmentAddress
    }

    /**
     * Test the property 'shipmentContact'
     */
    @Test
    public void shipmentContactTest() {
        // TODO: test shipmentContact
    }

    /**
     * Test the property 'deliveredOn'
     */
    @Test
    public void deliveredOnTest() {
        // TODO: test deliveredOn
    }

    /**
     * Test the property 'productItems'
     */
    @Test
    public void productItemsTest() {
        // TODO: test productItems
    }

}
